### PR TITLE
Histogram default buckets fix

### PR DESCRIPTION
**Pull request by deadtrickster**
Hi,

As required by Prometheus client guides default buckets for histograms are decimal fractions of _seconds_. I personally prefer microseconds too - nice resolution and simple ets:update_counter. 
So in the first commit I override default buckets for duration histogram. Fell free to change buckets on your own discretion but this is what I'm using for prometheus-plugs (in fact I think I should add these buckets to prometheus.erl itself).

I also allowed myself to add two todos in the second commit. Let me know if you don't like it - I'll remove it.

### CODE REVIEW

**Comment by yurrriq** [comment]
Looks good to me. I like the idea of uniformity between prometheus-plugs and this elli_prometheus. This needs a rebase and I like no spaces between list/tuple elements.

**Comment by deadtrickster** [comment]
done

**Comment by yurrriq** [comment]
This can be closed since we've got #3 merged now, right?

**Comment by deadtrickster** [comment]
Yeah!

**Pull request closed without merging**
